export enum MediaProfile{
    JPEG_VIDEO_ONLY = 'JPEG_VIDEO_ONLY',
    KURENTO_SPLIT_RECORDER = 'KURENTO_SPLIT_RECORDER',
    MKV = 'MKV',
    MKV_AUDIO_ONLY = 'MKV_AUDIO_ONLY',
    MKV_VIDEO_ONLY = 'MKV_VIDEO_ONLY',
    MP4 = 'MP4',
    MP4_AUDIO_ONLY = 'MP4_AUDIO_ONLY',
    MP4_VIDEO_ONLY = 'MP4_VIDEO_ONLY',
    WEBM = 'WEBM',
    WEBM_AUDIO_ONLY = 'WEBM_AUDIO_ONLY',
    WEBM_VIDEO_ONLY = 'WEBM_VIDEO_ONLY'
}